"""BWAPI 4.4.0 enumerations (generated by scripts/gen_enums.py - do not edit).

Values are the raw BWAPI ids used on the wire (proto/bw.fbs).
"""
from enum import IntEnum

__all__ = ["UnitType", "Order", "TechType", "UpgradeType", "WeaponType", "Race", "UnitCommandType", "EventType", "PlayerType", "BulletType", "UnitSizeType", "DamageType", "ExplosionType", "GameType", "Error", "TextColor", "TextSize", "Color"]


class UnitType(IntEnum):
    Terran_Marine = 0
    Terran_Ghost = 1
    Terran_Vulture = 2
    Terran_Goliath = 3
    Terran_Goliath_Turret = 4
    Terran_Siege_Tank_Tank_Mode = 5
    Terran_Siege_Tank_Tank_Mode_Turret = 6
    Terran_SCV = 7
    Terran_Wraith = 8
    Terran_Science_Vessel = 9
    Hero_Gui_Montag = 10
    Terran_Dropship = 11
    Terran_Battlecruiser = 12
    Terran_Vulture_Spider_Mine = 13
    Terran_Nuclear_Missile = 14
    Terran_Civilian = 15
    Hero_Sarah_Kerrigan = 16
    Hero_Alan_Schezar = 17
    Hero_Alan_Schezar_Turret = 18
    Hero_Jim_Raynor_Vulture = 19
    Hero_Jim_Raynor_Marine = 20
    Hero_Tom_Kazansky = 21
    Hero_Magellan = 22
    Hero_Edmund_Duke_Tank_Mode = 23
    Hero_Edmund_Duke_Tank_Mode_Turret = 24
    Hero_Edmund_Duke_Siege_Mode = 25
    Hero_Edmund_Duke_Siege_Mode_Turret = 26
    Hero_Arcturus_Mengsk = 27
    Hero_Hyperion = 28
    Hero_Norad_II = 29
    Terran_Siege_Tank_Siege_Mode = 30
    Terran_Siege_Tank_Siege_Mode_Turret = 31
    Terran_Firebat = 32
    Spell_Scanner_Sweep = 33
    Terran_Medic = 34
    Zerg_Larva = 35
    Zerg_Egg = 36
    Zerg_Zergling = 37
    Zerg_Hydralisk = 38
    Zerg_Ultralisk = 39
    Zerg_Broodling = 40
    Zerg_Drone = 41
    Zerg_Overlord = 42
    Zerg_Mutalisk = 43
    Zerg_Guardian = 44
    Zerg_Queen = 45
    Zerg_Defiler = 46
    Zerg_Scourge = 47
    Hero_Torrasque = 48
    Hero_Matriarch = 49
    Zerg_Infested_Terran = 50
    Hero_Infested_Kerrigan = 51
    Hero_Unclean_One = 52
    Hero_Hunter_Killer = 53
    Hero_Devouring_One = 54
    Hero_Kukulza_Mutalisk = 55
    Hero_Kukulza_Guardian = 56
    Hero_Yggdrasill = 57
    Terran_Valkyrie = 58
    Zerg_Cocoon = 59
    Protoss_Corsair = 60
    Protoss_Dark_Templar = 61
    Zerg_Devourer = 62
    Protoss_Dark_Archon = 63
    Protoss_Probe = 64
    Protoss_Zealot = 65
    Protoss_Dragoon = 66
    Protoss_High_Templar = 67
    Protoss_Archon = 68
    Protoss_Shuttle = 69
    Protoss_Scout = 70
    Protoss_Arbiter = 71
    Protoss_Carrier = 72
    Protoss_Interceptor = 73
    Hero_Dark_Templar = 74
    Hero_Zeratul = 75
    Hero_Tassadar_Zeratul_Archon = 76
    Hero_Fenix_Zealot = 77
    Hero_Fenix_Dragoon = 78
    Hero_Tassadar = 79
    Hero_Mojo = 80
    Hero_Warbringer = 81
    Hero_Gantrithor = 82
    Protoss_Reaver = 83
    Protoss_Observer = 84
    Protoss_Scarab = 85
    Hero_Danimoth = 86
    Hero_Aldaris = 87
    Hero_Artanis = 88
    Critter_Rhynadon = 89
    Critter_Bengalaas = 90
    Special_Cargo_Ship = 91
    Special_Mercenary_Gunship = 92
    Critter_Scantid = 93
    Critter_Kakaru = 94
    Critter_Ragnasaur = 95
    Critter_Ursadon = 96
    Zerg_Lurker_Egg = 97
    Hero_Raszagal = 98
    Hero_Samir_Duran = 99
    Hero_Alexei_Stukov = 100
    Special_Map_Revealer = 101
    Hero_Gerard_DuGalle = 102
    Zerg_Lurker = 103
    Hero_Infested_Duran = 104
    Spell_Disruption_Web = 105
    Terran_Command_Center = 106
    Terran_Comsat_Station = 107
    Terran_Nuclear_Silo = 108
    Terran_Supply_Depot = 109
    Terran_Refinery = 110
    Terran_Barracks = 111
    Terran_Academy = 112
    Terran_Factory = 113
    Terran_Starport = 114
    Terran_Control_Tower = 115
    Terran_Science_Facility = 116
    Terran_Covert_Ops = 117
    Terran_Physics_Lab = 118
    Unused_Terran1 = 119
    Terran_Machine_Shop = 120
    Unused_Terran2 = 121
    Terran_Engineering_Bay = 122
    Terran_Armory = 123
    Terran_Missile_Turret = 124
    Terran_Bunker = 125
    Special_Crashed_Norad_II = 126
    Special_Ion_Cannon = 127
    Powerup_Uraj_Crystal = 128
    Powerup_Khalis_Crystal = 129
    Zerg_Infested_Command_Center = 130
    Zerg_Hatchery = 131
    Zerg_Lair = 132
    Zerg_Hive = 133
    Zerg_Nydus_Canal = 134
    Zerg_Hydralisk_Den = 135
    Zerg_Defiler_Mound = 136
    Zerg_Greater_Spire = 137
    Zerg_Queens_Nest = 138
    Zerg_Evolution_Chamber = 139
    Zerg_Ultralisk_Cavern = 140
    Zerg_Spire = 141
    Zerg_Spawning_Pool = 142
    Zerg_Creep_Colony = 143
    Zerg_Spore_Colony = 144
    Unused_Zerg1 = 145
    Zerg_Sunken_Colony = 146
    Special_Overmind_With_Shell = 147
    Special_Overmind = 148
    Zerg_Extractor = 149
    Special_Mature_Chrysalis = 150
    Special_Cerebrate = 151
    Special_Cerebrate_Daggoth = 152
    Unused_Zerg2 = 153
    Protoss_Nexus = 154
    Protoss_Robotics_Facility = 155
    Protoss_Pylon = 156
    Protoss_Assimilator = 157
    Unused_Protoss1 = 158
    Protoss_Observatory = 159
    Protoss_Gateway = 160
    Unused_Protoss2 = 161
    Protoss_Photon_Cannon = 162
    Protoss_Citadel_of_Adun = 163
    Protoss_Cybernetics_Core = 164
    Protoss_Templar_Archives = 165
    Protoss_Forge = 166
    Protoss_Stargate = 167
    Special_Stasis_Cell_Prison = 168
    Protoss_Fleet_Beacon = 169
    Protoss_Arbiter_Tribunal = 170
    Protoss_Robotics_Support_Bay = 171
    Protoss_Shield_Battery = 172
    Special_Khaydarin_Crystal_Form = 173
    Special_Protoss_Temple = 174
    Special_XelNaga_Temple = 175
    Resource_Mineral_Field = 176
    Resource_Mineral_Field_Type_2 = 177
    Resource_Mineral_Field_Type_3 = 178
    Unused_Cave = 179
    Unused_Cave_In = 180
    Unused_Cantina = 181
    Unused_Mining_Platform = 182
    Unused_Independant_Command_Center = 183
    Special_Independant_Starport = 184
    Unused_Independant_Jump_Gate = 185
    Unused_Ruins = 186
    Unused_Khaydarin_Crystal_Formation = 187
    Resource_Vespene_Geyser = 188
    Special_Warp_Gate = 189
    Special_Psi_Disrupter = 190
    Unused_Zerg_Marker = 191
    Unused_Terran_Marker = 192
    Unused_Protoss_Marker = 193
    Special_Zerg_Beacon = 194
    Special_Terran_Beacon = 195
    Special_Protoss_Beacon = 196
    Special_Zerg_Flag_Beacon = 197
    Special_Terran_Flag_Beacon = 198
    Special_Protoss_Flag_Beacon = 199
    Special_Power_Generator = 200
    Special_Overmind_Cocoon = 201
    Spell_Dark_Swarm = 202
    Special_Floor_Missile_Trap = 203
    Special_Floor_Hatch = 204
    Special_Upper_Level_Door = 205
    Special_Right_Upper_Level_Door = 206
    Special_Pit_Door = 207
    Special_Right_Pit_Door = 208
    Special_Floor_Gun_Trap = 209
    Special_Wall_Missile_Trap = 210
    Special_Wall_Flame_Trap = 211
    Special_Right_Wall_Missile_Trap = 212
    Special_Right_Wall_Flame_Trap = 213
    Special_Start_Location = 214
    Powerup_Flag = 215
    Powerup_Young_Chrysalis = 216
    Powerup_Psi_Emitter = 217
    Powerup_Data_Disk = 218
    Powerup_Khaydarin_Crystal = 219
    Powerup_Mineral_Cluster_Type_1 = 220
    Powerup_Mineral_Cluster_Type_2 = 221
    Powerup_Protoss_Gas_Orb_Type_1 = 222
    Powerup_Protoss_Gas_Orb_Type_2 = 223
    Powerup_Zerg_Gas_Sac_Type_1 = 224
    Powerup_Zerg_Gas_Sac_Type_2 = 225
    Powerup_Terran_Gas_Tank_Type_1 = 226
    Powerup_Terran_Gas_Tank_Type_2 = 227
    None_ = 228
    AllUnits = 229
    Men = 230
    Buildings = 231
    Factories = 232
    Unknown = 233
    MAX = 234

    @classmethod
    def get(cls, value: int) -> "UnitType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class Order(IntEnum):
    Die = 0
    Stop = 1
    Guard = 2
    PlayerGuard = 3
    TurretGuard = 4
    BunkerGuard = 5
    Move = 6
    ReaverStop = 7
    Attack1 = 8
    Attack2 = 9
    AttackUnit = 10
    AttackFixedRange = 11
    AttackTile = 12
    Hover = 13
    AttackMove = 14
    InfestedCommandCenter = 15
    UnusedNothing = 16
    UnusedPowerup = 17
    TowerGuard = 18
    TowerAttack = 19
    VultureMine = 20
    StayInRange = 21
    TurretAttack = 22
    Nothing = 23
    Unused_24 = 24
    DroneStartBuild = 25
    DroneBuild = 26
    CastInfestation = 27
    MoveToInfest = 28
    InfestingCommandCenter = 29
    PlaceBuilding = 30
    PlaceProtossBuilding = 31
    CreateProtossBuilding = 32
    ConstructingBuilding = 33
    Repair = 34
    MoveToRepair = 35
    PlaceAddon = 36
    BuildAddon = 37
    Train = 38
    RallyPointUnit = 39
    RallyPointTile = 40
    ZergBirth = 41
    ZergUnitMorph = 42
    ZergBuildingMorph = 43
    IncompleteBuilding = 44
    IncompleteMorphing = 45
    BuildNydusExit = 46
    EnterNydusCanal = 47
    IncompleteWarping = 48
    Follow = 49
    Carrier = 50
    ReaverCarrierMove = 51
    CarrierStop = 52
    CarrierAttack = 53
    CarrierMoveToAttack = 54
    CarrierIgnore2 = 55
    CarrierFight = 56
    CarrierHoldPosition = 57
    Reaver = 58
    ReaverAttack = 59
    ReaverMoveToAttack = 60
    ReaverFight = 61
    ReaverHoldPosition = 62
    TrainFighter = 63
    InterceptorAttack = 64
    ScarabAttack = 65
    RechargeShieldsUnit = 66
    RechargeShieldsBattery = 67
    ShieldBattery = 68
    InterceptorReturn = 69
    DroneLand = 70
    BuildingLand = 71
    BuildingLiftOff = 72
    DroneLiftOff = 73
    LiftingOff = 74
    ResearchTech = 75
    Upgrade = 76
    Larva = 77
    SpawningLarva = 78
    Harvest1 = 79
    Harvest2 = 80
    MoveToGas = 81
    WaitForGas = 82
    HarvestGas = 83
    ReturnGas = 84
    MoveToMinerals = 85
    WaitForMinerals = 86
    MiningMinerals = 87
    Harvest3 = 88
    Harvest4 = 89
    ReturnMinerals = 90
    Interrupted = 91
    EnterTransport = 92
    PickupIdle = 93
    PickupTransport = 94
    PickupBunker = 95
    Pickup4 = 96
    PowerupIdle = 97
    Sieging = 98
    Unsieging = 99
    WatchTarget = 100
    InitCreepGrowth = 101
    SpreadCreep = 102
    StoppingCreepGrowth = 103
    GuardianAspect = 104
    ArchonWarp = 105
    CompletingArchonSummon = 106
    HoldPosition = 107
    QueenHoldPosition = 108
    Cloak = 109
    Decloak = 110
    Unload = 111
    MoveUnload = 112
    FireYamatoGun = 113
    MoveToFireYamatoGun = 114
    CastLockdown = 115
    Burrowing = 116
    Burrowed = 117
    Unburrowing = 118
    CastDarkSwarm = 119
    CastParasite = 120
    CastSpawnBroodlings = 121
    CastEMPShockwave = 122
    NukeWait = 123
    NukeTrain = 124
    NukeLaunch = 125
    NukePaint = 126
    NukeUnit = 127
    CastNuclearStrike = 128
    NukeTrack = 129
    InitializeArbiter = 130
    CloakNearbyUnits = 131
    PlaceMine = 132
    RightClickAction = 133
    SuicideUnit = 134
    SuicideLocation = 135
    SuicideHoldPosition = 136
    CastRecall = 137
    Teleport = 138
    CastScannerSweep = 139
    Scanner = 140
    CastDefensiveMatrix = 141
    CastPsionicStorm = 142
    CastIrradiate = 143
    CastPlague = 144
    CastConsume = 145
    CastEnsnare = 146
    CastStasisField = 147
    CastHallucination = 148
    Hallucination2 = 149
    ResetCollision = 150
    ResetHarvestCollision = 151
    Patrol = 152
    CTFCOPInit = 153
    CTFCOPStarted = 154
    CTFCOP2 = 155
    ComputerAI = 156
    AtkMoveEP = 157
    HarassMove = 158
    AIPatrol = 159
    GuardPost = 160
    RescuePassive = 161
    Neutral = 162
    ComputerReturn = 163
    InitializePsiProvider = 164
    SelfDestructing = 165
    Critter = 166
    HiddenGun = 167
    OpenDoor = 168
    CloseDoor = 169
    HideTrap = 170
    RevealTrap = 171
    EnableDoodad = 172
    DisableDoodad = 173
    WarpIn = 174
    Medic = 175
    MedicHeal = 176
    HealMove = 177
    MedicHoldPosition = 178
    MedicHealToIdle = 179
    CastRestoration = 180
    CastDisruptionWeb = 181
    CastMindControl = 182
    DarkArchonMeld = 183
    CastFeedback = 184
    CastOpticalFlare = 185
    CastMaelstrom = 186
    JunkYardDog = 187
    Fatal = 188
    None_ = 189
    Unknown = 190
    MAX = 191

    @classmethod
    def get(cls, value: int) -> "Order | int":
        try:
            return cls(value)
        except ValueError:
            return value


class TechType(IntEnum):
    Stim_Packs = 0
    Lockdown = 1
    EMP_Shockwave = 2
    Spider_Mines = 3
    Scanner_Sweep = 4
    Tank_Siege_Mode = 5
    Defensive_Matrix = 6
    Irradiate = 7
    Yamato_Gun = 8
    Cloaking_Field = 9
    Personnel_Cloaking = 10
    Burrowing = 11
    Infestation = 12
    Spawn_Broodlings = 13
    Dark_Swarm = 14
    Plague = 15
    Consume = 16
    Ensnare = 17
    Parasite = 18
    Psionic_Storm = 19
    Hallucination = 20
    Recall = 21
    Stasis_Field = 22
    Archon_Warp = 23
    Restoration = 24
    Disruption_Web = 25
    Unused_26 = 26
    Mind_Control = 27
    Dark_Archon_Meld = 28
    Feedback = 29
    Optical_Flare = 30
    Maelstrom = 31
    Lurker_Aspect = 32
    Unused_33 = 33
    Healing = 34
    None_ = 44
    Nuclear_Strike = 45
    Unknown = 46
    MAX = 47

    @classmethod
    def get(cls, value: int) -> "TechType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class UpgradeType(IntEnum):
    Terran_Infantry_Armor = 0
    Terran_Vehicle_Plating = 1
    Terran_Ship_Plating = 2
    Zerg_Carapace = 3
    Zerg_Flyer_Carapace = 4
    Protoss_Ground_Armor = 5
    Protoss_Air_Armor = 6
    Terran_Infantry_Weapons = 7
    Terran_Vehicle_Weapons = 8
    Terran_Ship_Weapons = 9
    Zerg_Melee_Attacks = 10
    Zerg_Missile_Attacks = 11
    Zerg_Flyer_Attacks = 12
    Protoss_Ground_Weapons = 13
    Protoss_Air_Weapons = 14
    Protoss_Plasma_Shields = 15
    U_238_Shells = 16
    Ion_Thrusters = 17
    Titan_Reactor = 19
    Ocular_Implants = 20
    Moebius_Reactor = 21
    Apollo_Reactor = 22
    Colossus_Reactor = 23
    Ventral_Sacs = 24
    Antennae = 25
    Pneumatized_Carapace = 26
    Metabolic_Boost = 27
    Adrenal_Glands = 28
    Muscular_Augments = 29
    Grooved_Spines = 30
    Gamete_Meiosis = 31
    Metasynaptic_Node = 32
    Singularity_Charge = 33
    Leg_Enhancements = 34
    Scarab_Damage = 35
    Reaver_Capacity = 36
    Gravitic_Drive = 37
    Sensor_Array = 38
    Gravitic_Boosters = 39
    Khaydarin_Amulet = 40
    Apial_Sensors = 41
    Gravitic_Thrusters = 42
    Carrier_Capacity = 43
    Khaydarin_Core = 44
    Argus_Jewel = 47
    Argus_Talisman = 49
    Caduceus_Reactor = 51
    Chitinous_Plating = 52
    Anabolic_Synthesis = 53
    Charon_Boosters = 54
    Upgrade_60 = 60
    None_ = 61
    Unknown = 62
    MAX = 63

    @classmethod
    def get(cls, value: int) -> "UpgradeType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class WeaponType(IntEnum):
    Gauss_Rifle = 0
    Gauss_Rifle_Jim_Raynor = 1
    C_10_Canister_Rifle = 2
    C_10_Canister_Rifle_Sarah_Kerrigan = 3
    Fragmentation_Grenade = 4
    Fragmentation_Grenade_Jim_Raynor = 5
    Spider_Mines = 6
    Twin_Autocannons = 7
    Hellfire_Missile_Pack = 8
    Twin_Autocannons_Alan_Schezar = 9
    Hellfire_Missile_Pack_Alan_Schezar = 10
    Arclite_Cannon = 11
    Arclite_Cannon_Edmund_Duke = 12
    Fusion_Cutter = 13
    Gemini_Missiles = 15
    Burst_Lasers = 16
    Gemini_Missiles_Tom_Kazansky = 17
    Burst_Lasers_Tom_Kazansky = 18
    ATS_Laser_Battery = 19
    ATA_Laser_Battery = 20
    ATS_Laser_Battery_Hero = 21
    ATA_Laser_Battery_Hero = 22
    ATS_Laser_Battery_Hyperion = 23
    ATA_Laser_Battery_Hyperion = 24
    Flame_Thrower = 25
    Flame_Thrower_Gui_Montag = 26
    Arclite_Shock_Cannon = 27
    Arclite_Shock_Cannon_Edmund_Duke = 28
    Longbolt_Missile = 29
    Yamato_Gun = 30
    Nuclear_Strike = 31
    Lockdown = 32
    EMP_Shockwave = 33
    Irradiate = 34
    Claws = 35
    Claws_Devouring_One = 36
    Claws_Infested_Kerrigan = 37
    Needle_Spines = 38
    Needle_Spines_Hunter_Killer = 39
    Kaiser_Blades = 40
    Kaiser_Blades_Torrasque = 41
    Toxic_Spores = 42
    Spines = 43
    Acid_Spore = 46
    Acid_Spore_Kukulza = 47
    Glave_Wurm = 48
    Glave_Wurm_Kukulza = 49
    Seeker_Spores = 52
    Subterranean_Tentacle = 53
    Suicide_Infested_Terran = 54
    Suicide_Scourge = 55
    Parasite = 56
    Spawn_Broodlings = 57
    Ensnare = 58
    Dark_Swarm = 59
    Plague = 60
    Consume = 61
    Particle_Beam = 62
    Psi_Blades = 64
    Psi_Blades_Fenix = 65
    Phase_Disruptor = 66
    Phase_Disruptor_Fenix = 67
    Psi_Assault = 69
    Psionic_Shockwave = 70
    Psionic_Shockwave_TZ_Archon = 71
    Dual_Photon_Blasters = 73
    Anti_Matter_Missiles = 74
    Dual_Photon_Blasters_Mojo = 75
    Anti_Matter_Missiles_Mojo = 76
    Phase_Disruptor_Cannon = 77
    Phase_Disruptor_Cannon_Danimoth = 78
    Pulse_Cannon = 79
    STS_Photon_Cannon = 80
    STA_Photon_Cannon = 81
    Scarab = 82
    Stasis_Field = 83
    Psionic_Storm = 84
    Warp_Blades_Zeratul = 85
    Warp_Blades_Hero = 86
    Platform_Laser_Battery = 92
    Independant_Laser_Battery = 93
    Twin_Autocannons_Floor_Trap = 96
    Hellfire_Missile_Pack_Wall_Trap = 97
    Flame_Thrower_Wall_Trap = 98
    Hellfire_Missile_Pack_Floor_Trap = 99
    Neutron_Flare = 100
    Disruption_Web = 101
    Restoration = 102
    Halo_Rockets = 103
    Corrosive_Acid = 104
    Mind_Control = 105
    Feedback = 106
    Optical_Flare = 107
    Maelstrom = 108
    Subterranean_Spines = 109
    Warp_Blades = 111
    C_10_Canister_Rifle_Samir_Duran = 112
    C_10_Canister_Rifle_Infested_Duran = 113
    Dual_Photon_Blasters_Artanis = 114
    Anti_Matter_Missiles_Artanis = 115
    C_10_Canister_Rifle_Alexei_Stukov = 116
    None_ = 130
    Unknown = 131
    MAX = 132

    @classmethod
    def get(cls, value: int) -> "WeaponType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class Race(IntEnum):
    Zerg = 0
    Terran = 1
    Protoss = 2
    Other = 3
    Unused = 4
    Select = 5
    Random = 6
    None_ = 7
    Unknown = 8
    MAX = 9

    @classmethod
    def get(cls, value: int) -> "Race | int":
        try:
            return cls(value)
        except ValueError:
            return value


class UnitCommandType(IntEnum):
    Attack_Move = 0
    Attack_Unit = 1
    Build = 2
    Build_Addon = 3
    Train = 4
    Morph = 5
    Research = 6
    Upgrade = 7
    Set_Rally_Position = 8
    Set_Rally_Unit = 9
    Move = 10
    Patrol = 11
    Hold_Position = 12
    Stop = 13
    Follow = 14
    Gather = 15
    Return_Cargo = 16
    Repair = 17
    Burrow = 18
    Unburrow = 19
    Cloak = 20
    Decloak = 21
    Siege = 22
    Unsiege = 23
    Lift = 24
    Land = 25
    Load = 26
    Unload = 27
    Unload_All = 28
    Unload_All_Position = 29
    Right_Click_Position = 30
    Right_Click_Unit = 31
    Halt_Construction = 32
    Cancel_Construction = 33
    Cancel_Addon = 34
    Cancel_Train = 35
    Cancel_Train_Slot = 36
    Cancel_Morph = 37
    Cancel_Research = 38
    Cancel_Upgrade = 39
    Use_Tech = 40
    Use_Tech_Position = 41
    Use_Tech_Unit = 42
    Place_COP = 43
    None_ = 44
    Unknown = 45
    MAX = 46

    @classmethod
    def get(cls, value: int) -> "UnitCommandType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class EventType(IntEnum):
    MatchStart = 0
    MatchEnd = 1
    MatchFrame = 2
    MenuFrame = 3
    SendText = 4
    ReceiveText = 5
    PlayerLeft = 6
    NukeDetect = 7
    UnitDiscover = 8
    UnitEvade = 9
    UnitShow = 10
    UnitHide = 11
    UnitCreate = 12
    UnitDestroy = 13
    UnitMorph = 14
    UnitRenegade = 15
    SaveGame = 16
    UnitComplete = 17
    None_ = 18

    @classmethod
    def get(cls, value: int) -> "EventType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class PlayerType(IntEnum):
    None_ = 0
    Computer = 1
    Player = 2
    RescuePassive = 3
    RescueActive = 4
    EitherPreferComputer = 5
    EitherPreferHuman = 6
    Neutral = 7
    Closed = 8
    Observer = 9
    PlayerLeft = 10
    ComputerLeft = 11
    Unknown = 12
    MAX = 13

    @classmethod
    def get(cls, value: int) -> "PlayerType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class BulletType(IntEnum):
    Melee = 0
    Fusion_Cutter_Hit = 141
    Gauss_Rifle_Hit = 142
    C_10_Canister_Rifle_Hit = 143
    Gemini_Missiles = 144
    Fragmentation_Grenade = 145
    Longbolt_Missile = 146
    Unused_Lockdown = 147
    ATS_ATA_Laser_Battery = 148
    Burst_Lasers = 149
    Arclite_Shock_Cannon_Hit = 150
    EMP_Missile = 151
    Dual_Photon_Blasters_Hit = 152
    Particle_Beam_Hit = 153
    Anti_Matter_Missile = 154
    Pulse_Cannon = 155
    Psionic_Shockwave_Hit = 156
    Psionic_Storm = 157
    Yamato_Gun = 158
    Phase_Disruptor = 159
    STA_STS_Cannon_Overlay = 160
    Sunken_Colony_Tentacle = 161
    Venom_Unused = 162
    Acid_Spore = 163
    Plasma_Drip_Unused = 164
    Glave_Wurm = 165
    Seeker_Spores = 166
    Queen_Spell_Carrier = 167
    Plague_Cloud = 168
    Consume = 169
    Ensnare = 170
    Needle_Spine_Hit = 171
    Invisible = 172
    Optical_Flare_Grenade = 201
    Halo_Rockets = 202
    Subterranean_Spines = 203
    Corrosive_Acid_Shot = 204
    Corrosive_Acid_Hit = 205
    Neutron_Flare = 206
    None_ = 209
    Unknown = 210
    MAX = 211

    @classmethod
    def get(cls, value: int) -> "BulletType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class UnitSizeType(IntEnum):
    Independent = 0
    Small = 1
    Medium = 2
    Large = 3
    None_ = 4
    Unknown = 5
    MAX = 6

    @classmethod
    def get(cls, value: int) -> "UnitSizeType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class DamageType(IntEnum):
    Independent = 0
    Explosive = 1
    Concussive = 2
    Normal = 3
    Ignore_Armor = 4
    None_ = 5
    Unknown = 6
    MAX = 7

    @classmethod
    def get(cls, value: int) -> "DamageType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class ExplosionType(IntEnum):
    None_ = 0
    Normal = 1
    Radial_Splash = 2
    Enemy_Splash = 3
    Lockdown = 4
    Nuclear_Missile = 5
    Parasite = 6
    Broodlings = 7
    EMP_Shockwave = 8
    Irradiate = 9
    Ensnare = 10
    Plague = 11
    Stasis_Field = 12
    Dark_Swarm = 13
    Consume = 14
    Yamato_Gun = 15
    Restoration = 16
    Disruption_Web = 17
    Corrosive_Acid = 18
    Mind_Control = 19
    Feedback = 20
    Optical_Flare = 21
    Maelstrom = 22
    Unused = 23
    Air_Splash = 24
    Unknown = 25
    MAX = 26

    @classmethod
    def get(cls, value: int) -> "ExplosionType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class GameType(IntEnum):
    None_ = 0
    Custom = 1
    Melee = 2
    Free_For_All = 3
    One_on_One = 4
    Capture_The_Flag = 5
    Greed = 6
    Slaughter = 7
    Sudden_Death = 8
    Ladder = 9
    Use_Map_Settings = 10
    Team_Melee = 11
    Team_Free_For_All = 12
    Team_Capture_The_Flag = 13
    Unknown_0x0E = 14
    Top_vs_Bottom = 15
    Iron_Man_Ladder = 16
    Pro_Gamer_League = 32
    Unknown = 33
    MAX = 34

    @classmethod
    def get(cls, value: int) -> "GameType | int":
        try:
            return cls(value)
        except ValueError:
            return value


class Error(IntEnum):
    Unit_Does_Not_Exist = 0
    Unit_Not_Visible = 1
    Unit_Not_Owned = 2
    Unit_Busy = 3
    Incompatible_UnitType = 4
    Incompatible_TechType = 5
    Incompatible_State = 6
    Already_Researched = 7
    Fully_Upgraded = 8
    Currently_Researching = 9
    Currently_Upgrading = 10
    Insufficient_Minerals = 11
    Insufficient_Gas = 12
    Insufficient_Supply = 13
    Insufficient_Energy = 14
    Insufficient_Tech = 15
    Insufficient_Ammo = 16
    Insufficient_Space = 17
    Invalid_Tile_Position = 18
    Unbuildable_Location = 19
    Unreachable_Location = 20
    Out_Of_Range = 21
    Unable_To_Hit = 22
    Access_Denied = 23
    File_Not_Found = 24
    Invalid_Parameter = 25
    None_ = 26
    Unknown = 27
    MAX = 28

    @classmethod
    def get(cls, value: int) -> "Error | int":
        try:
            return cls(value)
        except ValueError:
            return value


class TextColor(IntEnum):
    Previous = 1
    Default = 2
    Yellow = 3
    White = 4
    Grey = 5
    Red = 6
    Green = 7
    BrightRed = 8
    Invisible = 11
    Blue = 14
    Teal = 15
    Purple = 16
    Orange = 17
    Align_Right = 18
    Align_Center = 19
    Invisible2 = 20
    Brown = 21
    PlayerWhite = 22
    PlayerYellow = 23
    DarkGreen = 24
    LightYellow = 25
    Cyan = 26
    Tan = 27
    GreyBlue = 28
    GreyGreen = 29
    GreyCyan = 30
    Turquoise = 31

    @classmethod
    def get(cls, value: int) -> "TextColor | int":
        try:
            return cls(value)
        except ValueError:
            return value


class TextSize(IntEnum):
    Small = 0
    Default = 1
    Large = 2
    Huge = 3

    @classmethod
    def get(cls, value: int) -> "TextSize | int":
        try:
            return cls(value)
        except ValueError:
            return value


class Color(IntEnum):
    Red = 111
    Blue = 165
    Teal = 159
    Purple = 164
    Orange = 156
    Brown = 19
    White = 255
    Yellow = 135
    Green = 117
    Cyan = 128
    Black = 0
    Grey = 74

    @classmethod
    def get(cls, value: int) -> "Color | int":
        try:
            return cls(value)
        except ValueError:
            return value

