#!/usr/bin/env python3
"""Generate python/bwbot/enums.py from the vendored BWAPI 4.4.0 headers.

The numeric values are the wire format (see proto/bw.fbs), so they must match BWAPI exactly.
Run after changing the vendored headers:  python scripts/gen_enums.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INC = ROOT / "shim" / "third_party" / "bwapi" / "include" / "BWAPI"
OUT = ROOT / "python" / "bwbot" / "enums.py"

# (python class name, header file, enclosing C++ namespace whose `enum Enum` we want)
TABLES = [
    ("UnitType", "UnitType.h", "UnitTypes"),
    ("Order", "Order.h", "Orders"),
    ("TechType", "TechType.h", "TechTypes"),
    ("UpgradeType", "UpgradeType.h", "UpgradeTypes"),
    ("WeaponType", "WeaponType.h", "WeaponTypes"),
    ("Race", "Race.h", "Races"),
    ("UnitCommandType", "UnitCommandType.h", "UnitCommandTypes"),
    ("EventType", "EventType.h", "EventType"),
    ("PlayerType", "PlayerType.h", "PlayerTypes"),
    ("BulletType", "BulletType.h", "BulletTypes"),
    ("UnitSizeType", "UnitSizeType.h", "UnitSizeTypes"),
    ("DamageType", "DamageType.h", "DamageTypes"),
    ("ExplosionType", "ExplosionType.h", "ExplosionTypes"),
    ("GameType", "GameType.h", "GameTypes"),
    ("Error", "Error.h", "Errors"),
    ("TextColor", "Color.h", "Text"),
    ("TextSize", "Color.h", "Size"),
]

# `namespace Colors { constexpr Color Red{ 111 }; ... }` - palette indices, not an enum.
CONSTEXPR_TABLES = [
    ("Color", "Color.h", "Colors", r"constexpr\s+Color\s+(\w+)\s*\{\s*(\d+)\s*\}"),
]

# BWAPI names that are Python keywords/builtins get a trailing underscore (e.g. UnitType.None_).
PY_RESERVED = {"None", "True", "False", "class", "def", "return", "import", "from", "pass", "in", "is", "and", "or", "not", "if", "else", "for", "while", "with", "as", "del", "try", "except", "lambda", "yield", "global", "assert", "break", "continue", "raise", "finally", "nonlocal"}

ENUM_RE = re.compile(r"namespace\s+(\w+)\s*\{(.*?)enum\s+Enum\s*\{(.*?)\}", re.S)


def strip_comments(src: str) -> str:
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    src = re.sub(r"//[^\n]*", "", src)
    return src


def parse_enum(body: str) -> list[tuple[str, int]]:
    items: list[tuple[str, int]] = []
    value = -1
    for raw in body.split(","):
        raw = raw.strip()
        if not raw:
            continue
        m = re.match(r"(\w+)\s*(?:=\s*(.+))?$", raw, re.S)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        if expr is not None:
            expr = expr.strip()
            # allow references to earlier names, e.g. `Unknown = MAX - 1` is not used, but hex/ints are
            env = {n: v for n, v in items}
            value = int(eval(expr, {"__builtins__": {}}, env))  # noqa: S307 - trusted BWAPI headers
        else:
            value += 1
        items.append((name, value))
    return items


def find_enum(src: str, namespace: str) -> list[tuple[str, int]]:
    # Find `namespace <namespace> { ... enum Enum { ... }` where the enum is the *nearest*.
    idx = 0
    while True:
        m = re.search(r"namespace\s+" + re.escape(namespace) + r"\b", src[idx:])
        if not m:
            raise SystemExit(f"namespace {namespace} not found")
        start = idx + m.end()
        e = re.search(r"enum\s+Enum\s*\{", src[start:])
        if not e:
            raise SystemExit(f"enum Enum after namespace {namespace} not found")
        body_start = start + e.end()
        body_end = src.index("}", body_start)
        between = src[start:body_start]
        # ensure we didn't skip into a different namespace (only `{`, `namespace Enum {` allowed between)
        if re.fullmatch(r"\s*\{\s*(namespace\s+Enum\s*\{\s*)?enum\s+Enum\s*\{", between, re.S):
            return parse_enum(src[body_start:body_end])
        idx = body_end


def main() -> None:
    out = [
        '"""BWAPI 4.4.0 enumerations (generated by scripts/gen_enums.py - do not edit).',
        "",
        "Values are the raw BWAPI ids used on the wire (proto/bw.fbs).",
        '"""',
        "from enum import IntEnum",
        "",
        "__all__ = [" + ", ".join(f'"{n}"' for n, _, _ in TABLES) + ", "
        + ", ".join(f'"{n}"' for n, _, _, _ in CONSTEXPR_TABLES) + "]",
        "",
    ]
    all_tables: list[tuple[str, list[tuple[str, int]]]] = []
    for cls, header, ns in TABLES:
        src = strip_comments((INC / header).read_text(encoding="utf-8", errors="replace"))
        all_tables.append((cls, find_enum(src, ns)))
    for cls, header, ns, pattern in CONSTEXPR_TABLES:
        src = strip_comments((INC / header).read_text(encoding="utf-8", errors="replace"))
        m = re.search(r"namespace\s+" + re.escape(ns) + r"\b", src)
        if not m:
            raise SystemExit(f"namespace {ns} not found")
        items = [(n, int(v)) for n, v in re.findall(pattern, src[m.end():])]
        all_tables.append((cls, items))

    for cls, items in all_tables:
        if not items:
            raise SystemExit(f"no items for {cls}")
        out.append("")
        out.append(f"class {cls}(IntEnum):")
        seen: set[int] = set()
        for name, value in items:
            if name in PY_RESERVED:
                name = name + "_"
            if name in ("MAX",):
                out.append(f"    MAX = {value}")
                continue
            if value in seen:
                out.append(f"    {name} = {value}  # alias")
            else:
                out.append(f"    {name} = {value}")
            seen.add(value)
        out.append("")
        out.append(f"    @classmethod")
        out.append(f"    def get(cls, value: int) -> \"{cls} | int\":")
        out.append(f"        try:")
        out.append(f"            return cls(value)")
        out.append(f"        except ValueError:")
        out.append(f"            return value")
        out.append("")

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(TABLES)} enums)")


if __name__ == "__main__":
    sys.exit(main())
