#!/usr/bin/env bash
# Regenerates FlatBuffers code from proto/bw.fbs (Linux/WSL counterpart of gen_proto.ps1).
# Usage: scripts/gen_proto.sh [path/to/flatc]
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLATC="${1:-${FLATC:-}}"
if [[ -z "$FLATC" ]]; then
  for c in "$ROOT/wsl/flatbuffers/flatc" "$ROOT/shim/build-openbw/_deps/flatbuffers-build/flatc" "$(command -v flatc || true)"; do
    if [[ -n "$c" && -x "$c" ]]; then FLATC="$c"; break; fi
  done
fi
if [[ -z "$FLATC" || ! -x "$FLATC" ]]; then
  echo "flatc not found; run scripts/setup_wsl.sh first or pass its path" >&2
  exit 1
fi

CPP_OUT="$ROOT/shim/generated"
PY_OUT="$ROOT/python/bwbot/generated"
mkdir -p "$CPP_OUT" "$PY_OUT"

"$FLATC" --cpp --scoped-enums --gen-object-api --cpp-std c++17 -o "$CPP_OUT" "$ROOT/proto/bw.fbs"
"$FLATC" --python --gen-onefile -o "$PY_OUT" "$ROOT/proto/bw.fbs"

# The one-file python output is named <schema>_generated.py; make it the package module bw.py.
pyfile="$(ls "$PY_OUT"/*_generated.py | head -n1)"
[[ -n "$pyfile" ]] || { echo "flatc produced no *_generated.py in $PY_OUT" >&2; exit 1; }
mv -f "$pyfile" "$PY_OUT/bw.py"
printf '# generated by scripts/gen_proto.sh - do not edit\nfrom . import bw  # noqa: F401\n' > "$PY_OUT/__init__.py"
echo "generated: $CPP_OUT/bw_generated.h, $PY_OUT/bw.py"
