# Regenerates FlatBuffers code from proto/bw.fbs:
#   shim/generated/bw_generated.h       (C++)
#   python/bwbot/generated/bw/*.py      (Python, one file per type)
[CmdletBinding()]
param([string]$Flatc = '')

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
if (-not $Flatc) { $Flatc = Join-Path $Root 'tools\flatc\flatc.exe' }
if (-not (Test-Path $Flatc)) { throw "flatc not found at $Flatc (run scripts\setup_windows.ps1)" }

$schema = Join-Path $Root 'proto\bw.fbs'
$cppOut = Join-Path $Root 'shim\generated'
$pyOut  = Join-Path $Root 'python\bwbot\generated'
New-Item -ItemType Directory -Force -Path $cppOut, $pyOut | Out-Null

& $Flatc --cpp --scoped-enums --gen-object-api --cpp-std c++17 -o $cppOut $schema
if ($LASTEXITCODE) { throw "flatc (cpp) failed" }

& $Flatc --python --gen-onefile -o $pyOut $schema
if ($LASTEXITCODE) { throw "flatc (python) failed" }

# The one-file python output is named after the schema; make it a package module.
$pyFile = Get-ChildItem $pyOut -Filter '*.py' | Where-Object { $_.Name -ne '__init__.py' } | Select-Object -First 1
if ($pyFile.Name -ne 'bw.py') { Move-Item $pyFile.FullName (Join-Path $pyOut 'bw.py') -Force }
Set-Content (Join-Path $pyOut '__init__.py') "# generated by scripts/gen_proto.ps1 - do not edit`nfrom . import bw  # noqa: F401`n"

Write-Host "generated: $cppOut\bw_generated.h, $pyOut\bw.py"
