<#
.SYNOPSIS
  One-shot Windows setup for the Brood War bot environment.

  - Verifies an MSVC (x86) toolchain is available (Visual Studio 2022 Community or Build Tools).
  - Downloads flatc (FlatBuffers compiler) into tools/flatc.
  - Downloads StarCraft: Brood War 1.16.1 + BWAPI 4.4.0 (redistributed with Blizzard's permission
    for AI research by David Churchill) into game/.
  - Downloads the BWAPI 4.4.0 source (client library) and vendors the needed parts into shim/third_party/bwapi.
  - Applies a client-mode bwapi.ini.
  - Creates the Python venv and installs the bwbot package.

  Safe to re-run; each step is skipped if its output already exists. Use -Force to redo everything.
#>
[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$SkipGame,
    [switch]$SkipPython
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$BuildDir = Join-Path $Root 'build'
$ToolsDir = Join-Path $Root 'tools'
$GameDir  = Join-Path $Root 'game'
New-Item -ItemType Directory -Force -Path $BuildDir, $ToolsDir, $GameDir | Out-Null

function Step($msg) { Write-Host "`n==> $msg" -ForegroundColor Cyan }

function Download($Url, $Out) {
    if ((Test-Path $Out) -and -not $Force) { Write-Host "  (exists) $Out"; return }
    Write-Host "  GET $Url"
    Invoke-WebRequest -Uri $Url -OutFile $Out -UserAgent 'Mozilla/5.0'
}

# ---------------------------------------------------------------------------
Step 'Checking MSVC toolchain'
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vsPath = $null
if (Test-Path $vswhere) {
    $vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
}
if (-not $vsPath) {
    Write-Host '  No MSVC C++ toolset found. Installing VS 2022 Build Tools with the C++ workload (several GB)...'
    winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --silent `
        --accept-package-agreements --accept-source-agreements `
        --override '--quiet --wait --norestart --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended'
    $vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if (-not $vsPath) { throw 'MSVC install failed. Install Visual Studio 2022 with "Desktop development with C++" manually.' }
}
Write-Host "  MSVC: $vsPath"
$vcvars = Join-Path $vsPath 'VC\Auxiliary\Build\vcvarsall.bat'
if (-not (Test-Path $vcvars)) { throw "vcvarsall.bat not found under $vsPath" }

# ---------------------------------------------------------------------------
Step 'flatc (FlatBuffers compiler)'
$flatc = Join-Path $ToolsDir 'flatc\flatc.exe'
if (-not (Test-Path $flatc) -or $Force) {
    $rel = Invoke-RestMethod -Uri 'https://api.github.com/repos/google/flatbuffers/releases/latest' -Headers @{ 'User-Agent' = 'bwbot-setup' }
    $asset = $rel.assets | Where-Object { $_.name -eq 'Windows.flatc.binary.zip' } | Select-Object -First 1
    Download $asset.browser_download_url (Join-Path $BuildDir 'flatc.zip')
    New-Item -ItemType Directory -Force -Path (Split-Path $flatc) | Out-Null
    Expand-Archive (Join-Path $BuildDir 'flatc.zip') -DestinationPath (Split-Path $flatc) -Force
}
& $flatc --version

# ---------------------------------------------------------------------------
Step 'BWAPI 4.4.0 source (client library, vendored into shim/third_party/bwapi)'
$bwapiZip = Join-Path $BuildDir 'bwapi-4.4.0.zip'
$bwapiSrc = Join-Path $BuildDir 'bwapi-src\bwapi-4.4.0\bwapi'
$vendor   = Join-Path $Root 'shim\third_party\bwapi'
if (-not (Test-Path (Join-Path $vendor 'include\BWAPI.h')) -or $Force) {
    Download 'https://github.com/bwapi/bwapi/archive/refs/tags/v4.4.0.zip' $bwapiZip
    Expand-Archive $bwapiZip -DestinationPath (Join-Path $BuildDir 'bwapi-src') -Force
    New-Item -ItemType Directory -Force -Path $vendor | Out-Null
    foreach ($d in 'include', 'BWAPILIB', 'BWAPIClient', 'Shared') {
        if (Test-Path (Join-Path $vendor $d)) { Remove-Item (Join-Path $vendor $d) -Recurse -Force }
        Copy-Item (Join-Path $bwapiSrc $d) (Join-Path $vendor $d) -Recurse
    }
    Copy-Item (Join-Path $BuildDir 'bwapi-src\bwapi-4.4.0\LICENSE') (Join-Path $vendor 'LICENSE') -Force -ErrorAction SilentlyContinue
    # Only sources are needed; drop MSBuild project files and the SWIG bindings.
    Get-ChildItem $vendor -Recurse -Include *.vcxproj, *.vcxproj.filters, *.vcxproj.user | Remove-Item -Force
    Remove-Item (Join-Path $vendor 'include\swig_lib') -Recurse -Force -ErrorAction SilentlyContinue
    # svnrev.h is normally produced by revisionUpdate.vbs at build time.
    Set-Content (Join-Path $vendor 'include\svnrev.h') "#pragma once`n// BWAPI 4.4.0 release revision (normally generated by bwapi/revisionUpdate.vbs).`nstatic const int SVN_REV = 2383;`n`n#include `"starcraftver.h`"`n"
}
Write-Host "  vendored at $vendor"

# ---------------------------------------------------------------------------
if (-not $SkipGame) {
    Step 'StarCraft: Brood War 1.16.1 + BWAPI 4.4.0 runtime -> game/'
    if (-not (Test-Path (Join-Path $GameDir 'StarCraft.exe')) -or $Force) {
        # Mirror maintained by David Churchill (Memorial University); the older cs.mun.ca URL now 404s.
        $zip = Join-Path $BuildDir 'scbw_bwapi440.zip'
        Download 'https://davechurchill.ca/starcraft/files/startcraft/scbw_bwapi440.zip' $zip
        $tmp = Join-Path $BuildDir 'scbw_extract'
        if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
        Expand-Archive $zip -DestinationPath $tmp -Force
        Get-ChildItem $tmp -Force | Move-Item -Destination $GameDir -Force
        Remove-Item $tmp -Recurse -Force
    }
    Write-Host "  game at $GameDir"

    Step 'bwapi.ini (client mode, auto single-player games)'
    $ini = Join-Path $GameDir 'bwapi-data\bwapi.ini'
    $c = Get-Content $ini -Raw
    $c = $c -replace '(?m)^ai\s*=.*$',            'ai     = ' `
           -replace '(?m)^ai_dbg\s*=.*$',        'ai_dbg = ' `
           -replace '(?m)^auto_menu\s*=.*$',     'auto_menu = SINGLE_PLAYER' `
           -replace '(?m)^character_name\s*=.*$','character_name = BwBot' `
           -replace '(?m)^map\s*=.*$',           'map = maps/BroodWar/sscai/(2)Destination.scx' `
           -replace '(?m)^race\s*=.*$',          'race = Terran' `
           -replace '(?m)^save_replay\s*=.*$',   'save_replay = maps/replays/bwbot/%MAP%_%BOTRACE%vs%ENEMYRACES%_$Y$b$d_$H$M$S.rep' `
           -replace '(?m)^sound\s*=.*$',         'sound = OFF' `
           -replace '(?m)^windowed\s*=.*$',      'windowed = ON' `
           -replace '(?m)^left\s*=.*$',          'left = 40' `
           -replace '(?m)^top\s*=.*$',           'top  = 40' `
           -replace '(?m)^width\s*=.*$',         'width  = 960' `
           -replace '(?m)^height\s*=.*$',        'height = 720'
    Set-Content $ini -Value $c -NoNewline
    New-Item -ItemType Directory -Force -Path (Join-Path $GameDir 'maps\replays\bwbot') | Out-Null
    Write-Host "  wrote $ini"

    Step 'disable "Show Tips at Startup" (registry; the dialog blocks the match)'
    $reg = 'HKCU:\Software\Blizzard Entertainment\Starcraft'
    if (-not (Test-Path $reg)) { New-Item $reg -Force | Out-Null }
    Set-ItemProperty $reg -Name tip -Value 0 -Type DWord
    Set-ItemProperty $reg -Name tipnum -Value 0 -Type DWord
}

# ---------------------------------------------------------------------------
Step 'Generating FlatBuffers code and BWAPI enums'
& (Join-Path $PSScriptRoot 'gen_proto.ps1')
python (Join-Path $PSScriptRoot 'gen_enums.py')

# ---------------------------------------------------------------------------
if (-not $SkipPython) {
    Step 'Python venv + bwbot package'
    $venv = Join-Path $Root 'python\.venv'
    if (-not (Test-Path (Join-Path $venv 'Scripts\python.exe'))) {
        python -m venv $venv
    }
    & (Join-Path $venv 'Scripts\python.exe') -m pip install --upgrade pip --quiet
    & (Join-Path $venv 'Scripts\python.exe') -m pip install -e (Join-Path $Root 'python') --quiet
    & (Join-Path $venv 'Scripts\python.exe') -c 'import bwbot, numpy, flatbuffers; print(f\"  bwbot {bwbot.__version__} numpy {numpy.__version__} flatbuffers {flatbuffers.__version__}\")'
}

Step 'Done'
Write-Host @"
Next:
  scripts\build_shim.ps1        # build shim\build\shim.exe (Win32)
  scripts\run_native.ps1        # launch StarCraft+BWAPI, shim, and the example bot
"@
